# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NetCli < Formula
  desc ""
  homepage "https://github.com/kirre02/net-cli"
  version "0.1.0"

  on_macos do
    url "https://github.com/kirre02/net-cli/releases/download/0.1.0/net-cli_0.1.0_darwin_all.tar.gz"
    sha256 "ca7c01c77e69a692f7b7fd18628bfd0fcfed23da7bd06e3bad69e7bdf73afc7b"

    def install
      bin.install "net-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kirre02/net-cli/releases/download/0.1.0/net-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "e0491a788b3a9ca6200457e370b7e8e6d68f5bcf0186910760514148e4008938"

      def install
        bin.install "net-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kirre02/net-cli/releases/download/0.1.0/net-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "94074959e0ff853d2e911ae36f1166a774a68514ccf8524a0bd79723409fe5fd"

      def install
        bin.install "net-cli"
      end
    end
  end
end
